Message-ID: <ff2ef422-3558-4df6-b180-70d749c88eec@fit.hcmus.edu.vn>
Date: Sat, 9 Dec 2023 22:01:18 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: receiver@yahoo.com.vn
From: Khanh Tran <sender@fit.hcmus.edu.vn>
Subject: ASAP
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

Hey, a asap mail sent.


