Content-Type: multipart/mixed; boundary="------------8Ojc6ce1RB3aowdf0OV41yuE"
Message-ID: <7abd2070-d09c-41dd-82f2-149c93ad3297@fit.hcmus.edu.vn>
Date: Mon, 11 Dec 2023 14:01:35 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: receiver@yahoo.com.vn
From: Khanh Tran <sender@fit.hcmus.edu.vn>
Subject: haha

This is a multi-part message in MIME format.
--------------8Ojc6ce1RB3aowdf0OV41yuE
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

asdkmasd


adaskd



sadlma



sadkas


sdakmdad



--------------8Ojc6ce1RB3aowdf0OV41yuE
Content-Type: text/plain; charset=UTF-8; name="Test.txt"
Content-Disposition: attachment; filename="Test.txt"
Content-Transfer-Encoding: base64

SGVsbG8NCkkgYW0gYSB0ZXh0IGZpbGUuDQpCeWU=

--------------8Ojc6ce1RB3aowdf0OV41yuE--
