Content-Type: multipart/mixed; boundary="boundary"
Date: Mon, 11 Dec 2023 14:16:50 +0700
MIME-Version: 1.0
To: receiver@yahoo.com.vn
Cc: 
From: Khanh Tran <receiver@yahoo.com.vn>
Subject: Hello, send mail eith code.

This is a multi-part message in MIME format.
--boundary
Content-Type: text/plain; charset=UTF-8; format=flowed

This is a mail send with code


No freak,,,,,

just check...

if there any bug



--boundary--
