Content-Type: multipart/mixed; boundary="boundary"
Date: Sun, 03 Dec 2023 19:41:10 +0700
MIME-Version: 1.0
To: receiver@yahoo.com.vn
Cc: 
From: Khanh Tran <sender@fit.hcmus.edu.vn>
Subject: aaa

This is a multi-part message in MIME format.
--boundary
Content-Type: text/plain; charset=UTF-8; format=flowed

aaa
aaa

--boundary
Content-Type: text/plain; charset=UTF-8; name="Test.txt"
Content-Disposition: attachment; filename="Test.txt"
Content-Transfer-Encoding: base64

SGVsbG8NCkkgYW0gYSB0ZXh0IGZpbGUuDQpCeWU=

--boundary--
