Message-ID: <9f823c6d-0252-4c9d-a064-0f6195dcb212@fit.hcmus.edu.vn>
Date: Mon, 11 Dec 2023 13:58:34 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: receiver@yahoo.com.vn
From: Khanh Tran <sender@fit.hcmus.edu.vn>
Subject: Hello tehre
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

abc

aac

asca

asalda

asdasd

s



sadasd


asdasd

sad



