Content-Type: multipart/mixed; boundary="boundary"
Date: Tue, 12 Dec 2023 14:09:52 +0700
MIME-Version: 1.0
To: receiver@yahoo.com.vn
Cc: 
From: Khanh Tran <receiver@yahoo.com.vn>
Subject: Hello. Send file exceed 3mb

This is a multi-part message in MIME format.
--boundary
Content-Type: text/plain; charset=UTF-8; format=flowed

hello
askdma

sadamd

sad



assd

--boundary
Content-Type: text/plain; charset=UTF-8; name="Test.txt"
Content-Disposition: attachment; filename="Test.txt"
Content-Transfer-Encoding: base64

SGVsbG8NCkkgYW0gYSB0ZXh0IGZpbGUuDQpCeWU=

--boundary--
