Message-ID: <f1947d7a-55d9-43b6-93a1-c0d5c0f8a08e@fit.hcmus.edu.vn>
Date: Sat, 9 Dec 2023 22:24:50 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: receiver@yahoo.com.vn
From: Khanh Tran <sender@fit.hcmus.edu.vn>
Subject: hello
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

jasndsa, virus, hack....

sadamdisjdmas

sdkmadsaodksa.

